apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: failk8s-operator

resources:
- secret_copier/resources/secret_copier_config.yaml
- secret_injector/resources/secret_injector_config.yaml
- resources/namespace.yaml
- resources/serviceaccount.yaml
- resources/rolebinding.yaml
- resources/deployment.yaml

#images:
#- name: registry.test/failk8s-operator
#  newName: registry.test.eduk8s.io/failk8s-operator
