apiVersion: failk8s.dev/v1alpha1
kind: SecretInjectorConfig
metadata:
  name: secret-injector-2
spec:
  rules:
  - sourceSecrets:
      labelSelector:
        matchLabels:
          pull-secret: "1"
    targetNamespaces:
      labelSelector:
        matchLabels:
          inject-pull-secrets: "1"
    serviceAccounts:
      labelSelector:
        matchLabels:
          inject-pull-secret: "1"
