apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: secret-copier-2
spec:
  rules:
  - sourceSecret:
      name: source-secret-1
      namespace: source-secrets
    targetNamespaces:
      labelSelector:
        matchLabels:
          copy-secrets: "1"
    targetSecret:
      name: target-secret-1
      labels:
        source-secret-label-3: "3"
        source-secret-label-4: "4"
