apiVersion: failk8s.dev/v1alpha1
kind: SecretInjectorConfig
metadata:
  name: secret-injector-1
spec:
  rules:
  - sourceSecrets:
      nameSelector:
        matchNames:
        - target-secret-1
    serviceAccounts:
      nameSelector:
        matchNames:
        - default
