apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: secret-copier-1
spec:
  rules:
  - sourceSecret:
      name: source-secret-1
      namespace: source-secrets
    targetNamespaces:
      nameSelector:
        matchNames:
        - target-secrets-1
        - target-secrets-2
    targetSecret:
      name: target-secret-1
      labels:
        source-secret-label-1: "1"
        source-secret-label-2: "2"
