apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: registry-credentials
spec:
  secrets:
  - name: registry-credentials
    namespace: registry
    targetNamespaces:
      nameSelector:
        matchNames:
        - example-1
        - example-2
    newName: failk8s-registry-credentials
    applyLabels:
      failk8s-pull-secret: "yes"
